# imagem base com Python
FROM python:3.8-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o script Python para o contêiner
COPY questao5.py .

# Execute o script Python quando o contêiner for iniciado
CMD ["python", "questao5.py"]